version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      #args:
        #  USER_ID: ${USER_ID}
        #  GROUP_ID: ${GROUP_ID}     
    ports:
      - "${PUBLIC_WEBSERVER_PORT}:80"
    depends_on:
      - cookiecutter
    links:
      - "cookiecutter"

  cookiecutter:
    build:
      context: .
      dockerfile: Dockerfile-cookiecutter
      #args:
        #  USER_ID: ${USER_ID}
        #  GROUP_ID: ${GROUP_ID}     
    ports:
      - 5006  
    volumes:
      - "${DATA_FOLDER}:/app/data"
  
